### ISSUE TITLE
The user's homeserver does not support the version of the room.

### ISSUE THREAD

**Issue by dillfrescott** [rednaks/matrix-webhooks#21]
Why does it say this when I try to invite it?

**Comment by rednaks** [comment]
Hello, @dillfrescott thank you for reporting this issue, I will look into it.
if you have a public room where I can test that would be nice.

**Comment by rednaks** [comment]
I was able to reproduce on a personal room, I'll look into it.

**Comment by rednaks** [comment]
I just upgraded matrix-webhooks homeserver, it supports rooms up to version 10. can you please confirm it's working ?

**Comment by dillfrescott** [comment]
Yes it is working! Thank you!
