### ISSUE TITLE
bot does not recognize PL over 100 as administrative, account is now blocked

### ISSUE THREAD

**Issue by williamkray** [rednaks/matrix-webhooks#28]
I just signed up today, verified my email address, and got my invite token for the bot.

I created a new room to test the webhook bot. At creation time, I set my PL to 101. I invited the bot, it joined, and then immediately left:

> @webhooks:matrix-webhooks.com left the room @my:account is not admin, not allowed to invite me in this room.

I lowered my PL to 100 and attempted to re-invite the bot, and got the following message:

> @webhooks:matrix-webhooks.com rejected the invitation Can't accept invitation, @my:account is blocked

**Comment by rednaks** [comment]
Hello @williamkray , thanks for opening the issue, currently we don't support custom PLs, but this would be a future feature.

we're a bit strick, when some one without permission tires to invite the bot, but it should be fine, it's only blocked for 1h.

Please let me know if you're able to invite the bot now, if not, please send a message to the support room in matrix and we will be able to take a look at the issue privately:   https://matrix.to/#/#matrix-webhooks-support:matrix.org

**Comment by williamkray** [comment]
still unable to invite to the room, says I'm not admin. my PL is 100.

I'll join your room and ping you later, thanks
